version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
     - POSTGRES_DB=bigmario_store
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=root
    ports:
      - '5433:5432'
    volumes:
      - db-postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=bigmario_store
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3307:3306'
    volumes:
      - db-mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - PMA_HOST=mysql
    ports:
      - '8080:80'
    depends_on:
      - mysql


volumes:
  db-postgres:
    driver: local
  db-mysql:
    driver: local
